name: Build

on:
  push: main
  pull_request:
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out client
        uses: actions/checkout@v2
        with:
          path: client
          submodules: recursive
      - name: Install dependencies
        working-directory: client
        run: |
          npm install
      - name: Build
        working-directory: client
        run: |
          npm run build
