name: Lint

on:
  push:
  pull_request:
jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out client
        uses: actions/checkout@v2
        with:
          path: client
          submodules: recursive
      - name: Install eslint
        working-directory: client
        run: |
          npm install eslint
      - name: Generate CSS types
        working-directory: client
        run: |
          npm run generate-css-types
      - name: Run eslint
        working-directory: client
        run: |
          npx eslint --max-warnings=0 .
